#!/bin/sh
#
# Starts containerd
#

DAEMON="containerd"
PIDFILE="/var/run/$DAEMON.pid"

start() {
        printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon --start --background --make-pidfile \
                --pidfile "$PIDFILE" --exec "/usr/bin/$DAEMON" \
                -O "/var/log/$DAEMON.log" 		
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}
stop() {
        printf 'Stopping %s: ' "$DAEMON"
        start-stop-daemon --stop --pidfile "$PIDFILE" --exec "/usr/sbin/$DAEMON"
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        rm -f "$PIDFILE"
        return "$status"
}
restart() {
        stop
        start
}

case "$1" in
  start)
      start
        ;;
  stop)
      stop
        ;;
  restart|reload)
      restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
